CANBUS:
  -
    Interface: nixnet
    Channel: CAN1
    BAUD: 500000
    DBC: "C:\\Users\\Public\\Documents\\Python Scripts\\pyHIL\\open_actuator.dbc"
    TX_LIST:
      - ControlCmd
      - TorqueSensorData
    
    RX_LIST:
      - TorqueSensorData
  # -
  #   Interface: socketcan
  #   Channel: can0
  #   BAUD: 500000
  #   DBC: "/home/mtitoo/pyHIL/open_actuator.dbc"
  #   TX_LIST:
  #     - ControlCmd
  #     - TorqueSensorData
    
  #   RX_LIST:
  #     - TorqueSensorData

  -
    Interface: nixnet
    Channel: CAN2
    BAUD: 500000
    DBC: "C:\\Users\\Public\\Documents\\Python Scripts\\pyHIL\\open_actuator.dbc"
    TX_LIST:
      - ControlCmd
      - TorqueSensorData
    
    RX_LIST:
      - TorqueSensorData

  # -
  #   Interface: socketcan
  #   Channel: vcan3
  #   BAUD: 500000
  #   DBC: "/home/mtitoo/pyHIL/open_actuator.dbc"
  #   TX_LIST:
  #     - ControlCmd
  #       - Torque
  #       - Speed
    
  #   RX_LIST:
  #     -DBG_DYNO
  #       - Torque
  #       - Speed

  # -
  #   Interface: socketcan
  #   Channel: vcan4
  #   BAUD: 500000
  #   DBC: "/home/mtitoo/pyHIL/open_actuator.dbc"
  #   TX_LIST:
  #     - ControlCmd
  #       - Torque
  #       - Speed
    
  #   RX_LIST:
  #     -DBG_DYNO
  #       - Torque
  #       - Speed

  # -
  #   Interface: socketcan
  #   Channel: vcan5
  #   BAUD: 500000
  #   DBC: "/home/mtitoo/pyHIL/open_actuator.dbc"
  #   TX_LIST:
  #     - ControlCmd
  #       - Torque
  #       - Speed
    
  #   RX_LIST:
  #     -DBG_DYNO
  #       - Torque
  #       - Speed

  # -
  #   Interface: socketcan
  #   Channel: vcan6
  #   BAUD: 500000
  #   DBC: "/home/mtitoo/pyHIL/open_actuator.dbc"
  #   TX_LIST:
  #     - ControlCmd
  #       - Torque
  #       - Speed
    
  #   RX_LIST:
  #     -DBG_DYNO
  #       - Torque
  #       - Speed